spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/rest-spring-boot
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
      format-sql: true
server:
  port: 9595
  servlet:
    context-path: /api